


services:
  safe:
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: ${database_url}
    depends_on:
      - db 

  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${password}
      POSTGRES_DB: ${dbname}
    # ports: 
    #   - 54325:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data: