


services:
  backend:
    build: .
    ports: 
      - 54322:5432

  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data: